// <auto-generated />
using System;
using FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Migrations
{
    [DbContext(typeof(EntityFrameworkContext))]
    partial class EntityFrameworkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Clientes.ClienteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("ATIVO");

                    b.Property<string>("Cpf")
                        .HasColumnType("text")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_ATUALIZACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_CRIACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_EXCLUSAO");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("CLIENTE", (string)null);
                });

            modelBuilder.Entity("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Pedidos.PagamentoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<Guid?>("ChaveMercadoPagoOrdem")
                        .HasColumnType("uuid")
                        .HasColumnName("CHAVE_MERCADO_PAGO_ORDEM");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_ATUALIZACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_CRIACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IdMercadoPagoOrdem")
                        .HasColumnType("text")
                        .HasColumnName("ID_MERCADO_PAGO_ORDEM");

                    b.Property<string>("IdMercadoPagoPagamento")
                        .HasColumnType("text")
                        .HasColumnName("ID_MERCADO_PAGO_PAGAMENTO");

                    b.Property<Guid?>("IdPedido")
                        .HasColumnType("uuid")
                        .HasColumnName("ID_PEDIDO");

                    b.Property<int>("Metodo")
                        .HasColumnType("integer")
                        .HasColumnName("METODO");

                    b.Property<string>("QrCode")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("IdPedido")
                        .IsUnique();

                    b.ToTable("PEDIDO_PAGAMENTO", (string)null);
                });

            modelBuilder.Entity("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Pedidos.PedidoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("ATIVO");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CODIGO");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_ATUALIZACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_CRIACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_EXCLUSAO");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uuid")
                        .HasColumnName("ID_CLIENTE");

                    b.Property<Guid?>("IdPagamento")
                        .HasColumnType("uuid")
                        .HasColumnName("ID_PAGAMENTO");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("VALOR_TOTAL");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("PEDIDO", (string)null);
                });

            modelBuilder.Entity("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Pedidos.PedidoItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("ATIVO");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CODIGO");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_ATUALIZACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_CRIACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_EXCLUSAO");

                    b.Property<Guid>("IdPedido")
                        .HasColumnType("uuid")
                        .HasColumnName("ID_PEDIDO");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uuid")
                        .HasColumnName("ID_PRODUTO");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("QUANTIDADE");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdProduto");

                    b.ToTable("PEDIDO_ITEM", (string)null);
                });

            modelBuilder.Entity("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Preparos.OrdemPedidoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_ATUALIZACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_CRIACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataFimPreparacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_FIM_PREPARACAO");

                    b.Property<DateTime?>("DataInicioPreparacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_INICIO_PREPARACAO");

                    b.Property<Guid>("IdPedido")
                        .HasColumnType("uuid")
                        .HasColumnName("ID_PEDIDO");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("IdPedido")
                        .IsUnique();

                    b.ToTable("ORDEM_PEDIDO", (string)null);
                });

            modelBuilder.Entity("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Produtos.ProdutoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("ATIVO");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer")
                        .HasColumnName("CATEGORIA");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_ATUALIZACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_CRIACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_EXCLUSAO");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("NOME");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric")
                        .HasColumnName("PRECO");

                    b.HasKey("Id");

                    b.ToTable("PRODUTO", (string)null);
                });

            modelBuilder.Entity("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Produtos.ProdutoImagemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("ATIVO");

                    b.Property<byte[]>("Conteudo")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("CONTEUDO");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_ATUALIZACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_CRIACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATA_EXCLUSAO");

                    b.Property<Guid?>("IdProduto")
                        .HasColumnType("uuid")
                        .HasColumnName("ID_PRODUTO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("NOME");

                    b.Property<decimal>("Tamanho")
                        .HasColumnType("numeric")
                        .HasColumnName("TAMANHO");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.HasIndex("IdProduto");

                    b.ToTable("PRODUTO_IMAGEM", (string)null);
                });

            modelBuilder.Entity("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Pedidos.PagamentoEntity", b =>
                {
                    b.HasOne("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Pedidos.PedidoEntity", "Pedido")
                        .WithOne("Pagamento")
                        .HasForeignKey("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Pedidos.PagamentoEntity", "IdPedido")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Pedidos.PedidoEntity", b =>
                {
                    b.HasOne("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Clientes.ClienteEntity", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Pedidos.PedidoItemEntity", b =>
                {
                    b.HasOne("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Pedidos.PedidoEntity", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Produtos.ProdutoEntity", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Preparos.OrdemPedidoEntity", b =>
                {
                    b.HasOne("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Pedidos.PedidoEntity", "Pedido")
                        .WithOne("OrdemPedido")
                        .HasForeignKey("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Preparos.OrdemPedidoEntity", "IdPedido")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Produtos.ProdutoImagemEntity", b =>
                {
                    b.HasOne("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Produtos.ProdutoEntity", "Produto")
                        .WithMany("Imagens")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_PRODUTO_IMAGEM_PRODUTO");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Clientes.ClienteEntity", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Pedidos.PedidoEntity", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("OrdemPedido");

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("FoodChallenge.Infrastructure.Data.Postgres.EntityFramework.Repositories.Produtos.ProdutoEntity", b =>
                {
                    b.Navigation("Imagens");
                });
#pragma warning restore 612, 618
        }
    }
}
